# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0037_scene_last_filename_tag_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='actoralias',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 13, 17, 49, 7, 453423)),
            preserve_default=False,
        ),
    ]
