# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_actoralias_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 30, 19, 57, 0, 286006)),
            preserve_default=False,
        ),
    ]
