# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_folder_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='actortag',
            name='actor_tag_alias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scenetag',
            name='scene_tag_alias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='website',
            name='website_alias',
            field=models.TextField(blank=True, default=''),
        ),
    ]
