# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0040_auto_20160831_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 21, 24, 7, 530369)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actortag',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 21, 24, 18, 632381)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 21, 24, 29, 587075)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 21, 25, 10, 550512)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenetag',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 21, 25, 20, 199796)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 21, 25, 27, 937852)),
            preserve_default=False,
        ),
    ]
