# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0041_auto_20160831_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='actortag',
            name='scene_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='actor_tags', to='videos.SceneTag'),
        ),
    ]
