# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0042_actortag_scene_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='date_last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
