# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0043_scene_date_last_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('scenes', models.ManyToManyField(null=True, related_name='playlists', to='videos.Scene')),
            ],
        ),
    ]
