# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0044_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='scenes',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', to='videos.Scene'),
        ),
    ]
