# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0045_auto_20160907_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='localscenefolders',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 8, 16, 16, 23, 45064)),
            preserve_default=False,
        ),
    ]
